/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import game_model.Board;
import game_model.Scrabble;
import java.awt.Canvas;
import java.awt.Color;
import java.awt.Graphics;
import scrabble_client.ClientService;

/**@author  Adam Kopnicky
 *          Ewa Godlewska
 *          Flavio Dias
 *          Hugo Pereira
 *          Jose Carvalho
 */ 
public class GameGUI extends javax.swing.JFrame {
    
    public static Scrabble s;
    public static GameGUI frame;
    private Canvas boardCanvas;
    
    /**
     * Creates new form GameGUI
     */
    public GameGUI() {
        initComponents();
        ClientService clientService = ClientService.getInstance();
        clientService.setGameGui(this);
        boardCanvas = new Canvas()
        {
            private static final long serialVersionUID = 3678971088393809762L;
            public void paint(Graphics g)
            {
                drawBoard(g);	
                //drawPlayers(g);
            }
        };
        boardCanvas.setBackground(Color.WHITE);
        boardCanvas.setBounds(3, 3, 518, 518);
        boardPanel.add(boardCanvas);
        //drawPlayers(g);
        s = new Scrabble(1);
        s.firstLetters();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        ChatP = new javax.swing.JPanel();
        contentPane = new javax.swing.JPanel();
        tilePanel = new javax.swing.JPanel();
        boardPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        quitGameB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        ChatP.setMinimumSize(new java.awt.Dimension(270, 600));
        ChatP.setLayout(null);

        contentPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        contentPane.setMinimumSize(new java.awt.Dimension(530, 600));
        contentPane.setLayout(null);

        tilePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        tilePanel.setMinimumSize(new java.awt.Dimension(518, 60));
        tilePanel.setLayout(null);
        contentPane.add(tilePanel);
        tilePanel.setBounds(3, 530, 518, 60);

        boardPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        boardPanel.setFocusable(false);
        boardPanel.setMinimumSize(new java.awt.Dimension(518, 518));
        boardPanel.setLayout(null);
        contentPane.add(boardPanel);
        boardPanel.setBounds(3, 3, 518, 518);

        menuPanel.setPreferredSize(new java.awt.Dimension(270, 140));
        menuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        quitGameB.setText("QUIT");
        quitGameB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitGameBActionPerformed(evt);
            }
        });
        menuPanel.add(quitGameB, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(contentPane, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChatP, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPane, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ChatP, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(816, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void quitGameBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitGameBActionPerformed
        ClientService clientService = ClientService.getInstance();
        clientService.exitGame();
    }//GEN-LAST:event_quitGameBActionPerformed

    static void drawBoard(Graphics g)
    {
        for(int y=0; y<15; y++)
            for(int x=0; x<15; x++)
            {
		if(s.board.getLetter(x, y) != null)
		{
                    g.setColor (Color.yellow);
                    g.fill3DRect(4+x*34, 4+y*34, 30, 30, true);

                    g.setColor (Color.black);
                    g.drawString(s.board.getLetter(x, y).toString(), 17+x*30, 28+y*30);
		}
		else
		{
                    if (s.board.getPremiumColor(x, y) == Board.Pcolor.NO)
                    {
                        g.setColor (new Color(220, 220, 220));
                        g.fill3DRect(4+x*34, 4+y*34, 30, 30, true);
                    }
                    else if (s.board.getPremiumColor(x, y) == Board.Pcolor.TW)
                    {
                        g.setColor (new Color(255, 90, 90));
                        g.fill3DRect(4+x*34, 4+y*34, 30, 30, true);
                    }						
                    else if (s.board.getPremiumColor(x, y) == Board.Pcolor.DW)
                    {
                        g.setColor (new Color(255,187,163));
                        g.fill3DRect(4+x*34, 4+y*34, 30, 30, true);
                    }
                    else if (s.board.getPremiumColor(x, y) == Board.Pcolor.TL)
                    {
                        g.setColor (new Color(90, 90, 255));
                        g.fill3DRect(4+x*34, 4+y*34, 30, 30, true);
                    }
                    else if (s.board.getPremiumColor(x, y) == Board.Pcolor.DL)
                    {
                        g.setColor (new Color(200, 200, 255));
                        g.fill3DRect(4+x*34, 4+y*34, 30, 30, true);
                    }
                }
            }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameGUI().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ChatP;
    private javax.swing.JPanel boardPanel;
    private javax.swing.JPanel contentPane;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JButton quitGameB;
    private javax.swing.JPanel tilePanel;
    // End of variables declaration//GEN-END:variables
}
