/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.CardLayout;
import java.awt.Dimension;
import scrabble_client.*;
/**
 *
 * @author HUGUETA
 */
public class MainFrame extends javax.swing.JFrame {
    static private String username;
    String room = "";
    /**
     * Creates new form MainFrame1
     * @param user
     */
    public MainFrame(String user) {
        initComponents();
        MainFrame.username = user;
        ClientService clientService = ClientService.getInstance();
        clientService.setMainFrame(this);
        usernameL.setText(user);
    }

    private MainFrame() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        quitConfirm = new javax.swing.JDialog();
        NoB = new javax.swing.JButton();
        yesB = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        mainFramePanel = new javax.swing.JPanel();
        ChatP = new javax.swing.JPanel();
        TabsTableRank = new javax.swing.JTabbedPane();
        chatPanel = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        chatarea = new javax.swing.JTextArea();
        chatinput = new javax.swing.JTextField();
        playersPanel = new javax.swing.JPanel();
        profsOptPanel2 = new javax.swing.JPanel();
        inviteB2 = new javax.swing.JButton();
        sendmessageB2 = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        playerList2 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        menuBarSettings = new javax.swing.JPanel();
        homeB1 = new javax.swing.JButton();
        rankingB1 = new javax.swing.JButton();
        helpB1 = new javax.swing.JButton();
        settingsB1 = new javax.swing.JButton();
        logoutB1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        basePanel = new javax.swing.JPanel();
        mainPage = new javax.swing.JPanel();
        usernameL = new javax.swing.JLabel();
        welcome = new javax.swing.JLabel();
        joinB = new javax.swing.JButton();
        createB = new javax.swing.JButton();
        roomScrollPane = new javax.swing.JScrollPane();
        roomTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        rankingP = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        settingsPage = new javax.swing.JPanel();
        volumeL = new javax.swing.JLabel();
        volumeSlider = new javax.swing.JSlider();
        newEmailL = new javax.swing.JLabel();
        newEmailInput = new javax.swing.JTextField();
        confirmPassL = new javax.swing.JLabel();
        currentPassL = new javax.swing.JLabel();
        newPassL = new javax.swing.JLabel();
        currentPassInput = new javax.swing.JPasswordField();
        newPassInput = new javax.swing.JPasswordField();
        confirmPassInput = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        newRoomPage = new javax.swing.JPanel();
        roomNameLabel = new javax.swing.JLabel();
        PlayersNumber = new javax.swing.JComboBox<>();
        roomNameInput = new javax.swing.JTextField();
        privateGameCheckBox = new javax.swing.JCheckBox();
        backB = new javax.swing.JButton();
        createRoomB = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        roomOwnerPage = new javax.swing.JPanel();
        quitB = new javax.swing.JButton();
        startB = new javax.swing.JButton();
        playersGrid = new javax.swing.JPanel();
        player1 = new javax.swing.JLabel();
        player2 = new javax.swing.JLabel();
        player3 = new javax.swing.JLabel();
        player4 = new javax.swing.JLabel();
        player1Status = new javax.swing.JLabel();
        player2Status = new javax.swing.JLabel();
        player3Status = new javax.swing.JLabel();
        player4Status = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        roomPage = new javax.swing.JPanel();
        quitRoomB = new javax.swing.JButton();
        readyB = new javax.swing.JButton();
        playersRoomGrid = new javax.swing.JPanel();
        player5 = new javax.swing.JLabel();
        player6 = new javax.swing.JLabel();
        player7 = new javax.swing.JLabel();
        player8 = new javax.swing.JLabel();
        player1Status1 = new javax.swing.JLabel();
        player2Status1 = new javax.swing.JLabel();
        player3Status1 = new javax.swing.JLabel();
        player4Status1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        quitConfirm.setAlwaysOnTop(true);
        quitConfirm.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        quitConfirm.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        quitConfirm.setLocationRelativeTo(null);
        quitConfirm.setSize(new Dimension(400,200));

        NoB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        NoB.setText("No");
        NoB.setMaximumSize(null);
        NoB.setMinimumSize(new java.awt.Dimension(70, 40));
        NoB.setPreferredSize(new java.awt.Dimension(100, 40));
        NoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoBActionPerformed(evt);
            }
        });
        quitConfirm.getContentPane().add(NoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        yesB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        yesB.setText("Yes");
        yesB.setMaximumSize(null);
        yesB.setMinimumSize(new java.awt.Dimension(70, 40));
        yesB.setPreferredSize(new java.awt.Dimension(100, 40));
        yesB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesBActionPerformed(evt);
            }
        });
        quitConfirm.getContentPane().add(yesB, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel7.setText("Are You Sure?");
        quitConfirm.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));

        mainFramePanel.setName(""); // NOI18N
        mainFramePanel.setLayout(new java.awt.BorderLayout());

        ChatP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TabsTableRank.setMinimumSize(new java.awt.Dimension(235, 260));
        TabsTableRank.setPreferredSize(new java.awt.Dimension(235, 260));

        chatPanel.setLayout(new java.awt.GridBagLayout());

        jScrollPane7.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        chatarea.setEditable(false);
        chatarea.setColumns(20);
        chatarea.setRows(5);
        chatarea.setWrapStyleWord(true);
        jScrollPane7.setViewportView(chatarea);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        chatPanel.add(jScrollPane7, gridBagConstraints);

        chatinput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                chatinputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                chatinputFocusLost(evt);
            }
        });
        chatinput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatinputActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        chatPanel.add(chatinput, gridBagConstraints);

        TabsTableRank.addTab("Chat", chatPanel);

        playersPanel.setLayout(new java.awt.BorderLayout());

        profsOptPanel2.setMinimumSize(new java.awt.Dimension(222, 25));
        profsOptPanel2.setOpaque(false);
        profsOptPanel2.setPreferredSize(new java.awt.Dimension(232, 35));
        profsOptPanel2.setLayout(new java.awt.BorderLayout());

        inviteB2.setText("Invite To Play");
        inviteB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inviteB2ActionPerformed(evt);
            }
        });
        profsOptPanel2.add(inviteB2, java.awt.BorderLayout.CENTER);

        sendmessageB2.setText("Send Message");
        sendmessageB2.setOpaque(false);
        sendmessageB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendmessageB2ActionPerformed(evt);
            }
        });
        profsOptPanel2.add(sendmessageB2, java.awt.BorderLayout.LINE_START);

        playersPanel.add(profsOptPanel2, java.awt.BorderLayout.PAGE_END);

        playerList2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        playerList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                playerList2MouseReleased(evt);
            }
        });
        jScrollPane8.setViewportView(playerList2);

        playersPanel.add(jScrollPane8, java.awt.BorderLayout.CENTER);

        TabsTableRank.addTab("Jogadores", playersPanel);

        ChatP.add(TabsTableRank, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 220, 380));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pageBackground.png"))); // NOI18N
        jLabel5.setMaximumSize(new java.awt.Dimension(300, 550));
        jLabel5.setMinimumSize(new java.awt.Dimension(300, 550));
        jLabel5.setPreferredSize(new java.awt.Dimension(300, 550));
        ChatP.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        mainFramePanel.add(ChatP, java.awt.BorderLayout.EAST);

        menuBarSettings.setOpaque(false);
        menuBarSettings.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homeB1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        homeB1.setText("Home");
        homeB1.setMaximumSize(new java.awt.Dimension(140, 40));
        homeB1.setMinimumSize(new java.awt.Dimension(140, 40));
        homeB1.setPreferredSize(new java.awt.Dimension(140, 40));
        homeB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeB1ActionPerformed(evt);
            }
        });
        menuBarSettings.add(homeB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 5, -1, -1));

        rankingB1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rankingB1.setText("Ranking");
        rankingB1.setMaximumSize(new java.awt.Dimension(140, 40));
        rankingB1.setMinimumSize(new java.awt.Dimension(140, 40));
        rankingB1.setPreferredSize(new java.awt.Dimension(140, 40));
        rankingB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rankingB1ActionPerformed(evt);
            }
        });
        menuBarSettings.add(rankingB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 5, -1, -1));

        helpB1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        helpB1.setText("Help");
        helpB1.setMaximumSize(new java.awt.Dimension(140, 40));
        helpB1.setMinimumSize(new java.awt.Dimension(140, 40));
        helpB1.setPreferredSize(new java.awt.Dimension(140, 40));
        menuBarSettings.add(helpB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 5, -1, -1));

        settingsB1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        settingsB1.setText("Settings");
        settingsB1.setMaximumSize(new java.awt.Dimension(140, 40));
        settingsB1.setMinimumSize(new java.awt.Dimension(140, 40));
        settingsB1.setPreferredSize(new java.awt.Dimension(140, 40));
        settingsB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsB1ActionPerformed(evt);
            }
        });
        menuBarSettings.add(settingsB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 5, -1, -1));

        logoutB1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        logoutB1.setText("Logout");
        logoutB1.setMaximumSize(new java.awt.Dimension(140, 40));
        logoutB1.setMinimumSize(new java.awt.Dimension(140, 40));
        logoutB1.setPreferredSize(new java.awt.Dimension(140, 40));
        logoutB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutB1ActionPerformed(evt);
            }
        });
        menuBarSettings.add(logoutB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 5, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/barBackground.png"))); // NOI18N
        menuBarSettings.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 50));

        mainFramePanel.add(menuBarSettings, java.awt.BorderLayout.PAGE_START);

        basePanel.setLayout(new java.awt.CardLayout());

        mainPage.setOpaque(false);
        mainPage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernameL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        usernameL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        usernameL.setText("username");
        mainPage.add(usernameL, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 80, 30));

        welcome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        welcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcome.setText("Welcome");
        mainPage.add(welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 80, 30));

        joinB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        joinB.setText("Join Room");
        joinB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinBActionPerformed(evt);
            }
        });
        mainPage.add(joinB, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 180, 40));

        createB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        createB.setText("Create Room");
        createB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBActionPerformed(evt);
            }
        });
        mainPage.add(createB, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 180, 40));

        roomTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room", "Players", "Joinable", "Room Owner"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        roomTable.setRowHeight(30);
        roomTable.getTableHeader().setReorderingAllowed(false);
        roomScrollPane.setViewportView(roomTable);

        mainPage.add(roomScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 370, 180));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pageBackground.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(500, 550));
        jLabel1.setMinimumSize(new java.awt.Dimension(500, 550));
        jLabel1.setPreferredSize(new java.awt.Dimension(500, 550));
        mainPage.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        basePanel.add(mainPage, "mainP");

        rankingP.setMinimumSize(new java.awt.Dimension(500, 550));
        rankingP.setPreferredSize(new java.awt.Dimension(500, 550));
        rankingP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pageBackground.png"))); // NOI18N
        rankingP.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 550));

        basePanel.add(rankingP, "rankP");

        settingsPage.setOpaque(false);
        settingsPage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        volumeL.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        volumeL.setText("Volume");
        volumeL.setMinimumSize(new java.awt.Dimension(110, 30));
        volumeL.setPreferredSize(new java.awt.Dimension(110, 30));
        settingsPage.add(volumeL, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 80, -1));

        volumeSlider.setOrientation(javax.swing.JSlider.VERTICAL);
        volumeSlider.setMinimumSize(new java.awt.Dimension(200, 40));
        volumeSlider.setPreferredSize(new java.awt.Dimension(200, 40));
        settingsPage.add(volumeSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 40, 230));

        newEmailL.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        newEmailL.setText("New Email");
        newEmailL.setMaximumSize(new java.awt.Dimension(110, 30));
        newEmailL.setMinimumSize(new java.awt.Dimension(110, 30));
        newEmailL.setPreferredSize(new java.awt.Dimension(110, 30));
        settingsPage.add(newEmailL, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 200, -1));

        newEmailInput.setMinimumSize(new java.awt.Dimension(200, 40));
        newEmailInput.setPreferredSize(new java.awt.Dimension(200, 40));
        newEmailInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newEmailInputActionPerformed(evt);
            }
        });
        settingsPage.add(newEmailInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, -1, -1));

        confirmPassL.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        confirmPassL.setText("Confirm Password");
        confirmPassL.setMaximumSize(new java.awt.Dimension(110, 30));
        confirmPassL.setMinimumSize(new java.awt.Dimension(110, 30));
        confirmPassL.setPreferredSize(new java.awt.Dimension(110, 30));
        settingsPage.add(confirmPassL, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 200, -1));

        currentPassL.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        currentPassL.setText("Current Password");
        currentPassL.setMaximumSize(new java.awt.Dimension(110, 30));
        currentPassL.setMinimumSize(new java.awt.Dimension(110, 30));
        currentPassL.setPreferredSize(new java.awt.Dimension(110, 30));
        settingsPage.add(currentPassL, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 190, -1));

        newPassL.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        newPassL.setText("New Password");
        newPassL.setMaximumSize(new java.awt.Dimension(110, 30));
        newPassL.setMinimumSize(new java.awt.Dimension(110, 30));
        newPassL.setPreferredSize(new java.awt.Dimension(110, 30));
        settingsPage.add(newPassL, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 190, -1));

        currentPassInput.setMinimumSize(new java.awt.Dimension(200, 40));
        currentPassInput.setPreferredSize(new java.awt.Dimension(200, 40));
        settingsPage.add(currentPassInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        newPassInput.setMinimumSize(new java.awt.Dimension(200, 40));
        newPassInput.setPreferredSize(new java.awt.Dimension(200, 40));
        settingsPage.add(newPassInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        confirmPassInput.setMinimumSize(new java.awt.Dimension(200, 40));
        confirmPassInput.setPreferredSize(new java.awt.Dimension(200, 40));
        confirmPassInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmPassInputActionPerformed(evt);
            }
        });
        settingsPage.add(confirmPassInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("Confirm Changes");
        jButton1.setMaximumSize(new java.awt.Dimension(130, 60));
        jButton1.setMinimumSize(new java.awt.Dimension(130, 60));
        jButton1.setPreferredSize(new java.awt.Dimension(130, 60));
        settingsPage.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 220, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pageBackground.png"))); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(500, 550));
        jLabel3.setMinimumSize(new java.awt.Dimension(500, 550));
        jLabel3.setPreferredSize(new java.awt.Dimension(500, 550));
        settingsPage.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        basePanel.add(settingsPage, "card7");

        newRoomPage.setToolTipText("");
        newRoomPage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roomNameLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        roomNameLabel.setText("Room Name");
        roomNameLabel.setMaximumSize(null);
        roomNameLabel.setMinimumSize(new java.awt.Dimension(200, 40));
        roomNameLabel.setPreferredSize(new java.awt.Dimension(110, 30));
        newRoomPage.add(roomNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 140, -1));

        PlayersNumber.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        PlayersNumber.setMaximumRowCount(3);
        PlayersNumber.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2 Players", "3 Players", "4 Players" }));
        PlayersNumber.setMinimumSize(new java.awt.Dimension(200, 40));
        PlayersNumber.setPreferredSize(new java.awt.Dimension(200, 40));
        PlayersNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayersNumberActionPerformed(evt);
            }
        });
        newRoomPage.add(PlayersNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));

        roomNameInput.setMinimumSize(new java.awt.Dimension(200, 40));
        roomNameInput.setPreferredSize(new java.awt.Dimension(200, 40));
        roomNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomNameInputActionPerformed(evt);
            }
        });
        newRoomPage.add(roomNameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

        privateGameCheckBox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        privateGameCheckBox.setText("Private Game");
        privateGameCheckBox.setMaximumSize(null);
        privateGameCheckBox.setMinimumSize(new java.awt.Dimension(200, 40));
        privateGameCheckBox.setOpaque(false);
        privateGameCheckBox.setPreferredSize(new java.awt.Dimension(200, 40));
        privateGameCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                privateGameCheckBoxActionPerformed(evt);
            }
        });
        newRoomPage.add(privateGameCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));

        backB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        backB.setText("Back");
        backB.setMaximumSize(null);
        backB.setMinimumSize(new java.awt.Dimension(140, 40));
        backB.setPreferredSize(new java.awt.Dimension(100, 30));
        backB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBActionPerformed(evt);
            }
        });
        newRoomPage.add(backB, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, -1, -1));

        createRoomB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        createRoomB.setText("Create");
        createRoomB.setMaximumSize(null);
        createRoomB.setMinimumSize(new java.awt.Dimension(140, 40));
        createRoomB.setPreferredSize(new java.awt.Dimension(140, 40));
        createRoomB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createRoomBActionPerformed(evt);
            }
        });
        newRoomPage.add(createRoomB, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 305, 140, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pageBackground.png"))); // NOI18N
        jLabel6.setMaximumSize(new java.awt.Dimension(500, 550));
        jLabel6.setMinimumSize(new java.awt.Dimension(500, 550));
        jLabel6.setPreferredSize(new java.awt.Dimension(500, 550));
        newRoomPage.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        basePanel.add(newRoomPage, "newRoomP");

        roomOwnerPage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        quitB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        quitB.setText("QUIT");
        quitB.setMaximumSize(new java.awt.Dimension(110, 40));
        quitB.setMinimumSize(new java.awt.Dimension(110, 40));
        quitB.setPreferredSize(new java.awt.Dimension(110, 40));
        quitB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitBActionPerformed(evt);
            }
        });
        roomOwnerPage.add(quitB, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, -1, -1));

        startB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        startB.setText("START");
        startB.setMaximumSize(new java.awt.Dimension(110, 40));
        startB.setMinimumSize(new java.awt.Dimension(110, 40));
        startB.setPreferredSize(new java.awt.Dimension(110, 40));
        startB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBActionPerformed(evt);
            }
        });
        roomOwnerPage.add(startB, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, -1));

        playersGrid.setMinimumSize(new java.awt.Dimension(300, 148));
        playersGrid.setOpaque(false);
        playersGrid.setPreferredSize(new java.awt.Dimension(300, 148));
        playersGrid.setLayout(new java.awt.GridLayout(4, 2, 2, 2));

        player1.setBackground(new java.awt.Color(255, 255, 255));
        player1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        player1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        player1.setMinimumSize(new java.awt.Dimension(148, 37));
        player1.setOpaque(true);
        player1.setPreferredSize(new java.awt.Dimension(148, 37));
        playersGrid.add(player1);

        player2.setBackground(new java.awt.Color(255, 255, 255));
        player2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        player2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        player2.setText("Owner");
        player2.setMinimumSize(new java.awt.Dimension(148, 37));
        player2.setOpaque(true);
        player2.setPreferredSize(new java.awt.Dimension(148, 37));
        playersGrid.add(player2);

        player3.setBackground(new java.awt.Color(255, 255, 255));
        player3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        player3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        player3.setMinimumSize(new java.awt.Dimension(148, 37));
        player3.setOpaque(true);
        player3.setPreferredSize(new java.awt.Dimension(148, 37));
        playersGrid.add(player3);

        player4.setBackground(new java.awt.Color(255, 255, 255));
        player4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        player4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        player4.setMinimumSize(new java.awt.Dimension(148, 37));
        player4.setOpaque(true);
        player4.setPreferredSize(new java.awt.Dimension(148, 37));
        playersGrid.add(player4);

        player1Status.setBackground(new java.awt.Color(255, 255, 255));
        player1Status.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        player1Status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        player1Status.setMinimumSize(new java.awt.Dimension(148, 37));
        player1Status.setOpaque(true);
        player1Status.setPreferredSize(new java.awt.Dimension(148, 37));
        playersGrid.add(player1Status);

        player2Status.setBackground(new java.awt.Color(255, 255, 255));
        player2Status.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        player2Status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        player2Status.setMinimumSize(new java.awt.Dimension(148, 37));
        player2Status.setOpaque(true);
        player2Status.setPreferredSize(new java.awt.Dimension(148, 37));
        playersGrid.add(player2Status);

        player3Status.setBackground(new java.awt.Color(255, 255, 255));
        player3Status.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        player3Status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        player3Status.setMinimumSize(new java.awt.Dimension(148, 37));
        player3Status.setOpaque(true);
        player3Status.setPreferredSize(new java.awt.Dimension(148, 37));
        playersGrid.add(player3Status);

        player4Status.setBackground(new java.awt.Color(255, 255, 255));
        player4Status.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        player4Status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        player4Status.setMinimumSize(new java.awt.Dimension(148, 37));
        player4Status.setOpaque(true);
        player4Status.setPreferredSize(new java.awt.Dimension(148, 37));
        playersGrid.add(player4Status);

        roomOwnerPage.add(playersGrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pageBackground.png"))); // NOI18N
        jLabel8.setMaximumSize(new java.awt.Dimension(500, 550));
        jLabel8.setMinimumSize(new java.awt.Dimension(500, 550));
        jLabel8.setPreferredSize(new java.awt.Dimension(500, 550));
        roomOwnerPage.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        basePanel.add(roomOwnerPage, "roomOwnerP");

        roomPage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        quitRoomB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        quitRoomB.setText("QUIT");
        quitRoomB.setMaximumSize(new java.awt.Dimension(110, 40));
        quitRoomB.setMinimumSize(new java.awt.Dimension(110, 40));
        quitRoomB.setPreferredSize(new java.awt.Dimension(110, 40));
        quitRoomB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitRoomBActionPerformed(evt);
            }
        });
        roomPage.add(quitRoomB, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, -1, -1));

        readyB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        readyB.setText("READY");
        readyB.setMaximumSize(new java.awt.Dimension(110, 40));
        readyB.setMinimumSize(new java.awt.Dimension(110, 40));
        readyB.setPreferredSize(new java.awt.Dimension(110, 40));
        readyB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readyBActionPerformed(evt);
            }
        });
        roomPage.add(readyB, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, -1));

        playersRoomGrid.setMinimumSize(new java.awt.Dimension(300, 148));
        playersRoomGrid.setOpaque(false);
        playersRoomGrid.setPreferredSize(new java.awt.Dimension(300, 148));
        playersRoomGrid.setLayout(new java.awt.GridLayout(4, 2, 2, 2));

        player5.setBackground(new java.awt.Color(255, 255, 255));
        player5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        player5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        player5.setMinimumSize(new java.awt.Dimension(148, 37));
        player5.setOpaque(true);
        player5.setPreferredSize(new java.awt.Dimension(148, 37));
        playersRoomGrid.add(player5);

        player6.setBackground(new java.awt.Color(255, 255, 255));
        player6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        player6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        player6.setText("Owner");
        player6.setMinimumSize(new java.awt.Dimension(148, 37));
        player6.setOpaque(true);
        player6.setPreferredSize(new java.awt.Dimension(148, 37));
        playersRoomGrid.add(player6);

        player7.setBackground(new java.awt.Color(255, 255, 255));
        player7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        player7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        player7.setMinimumSize(new java.awt.Dimension(148, 37));
        player7.setOpaque(true);
        player7.setPreferredSize(new java.awt.Dimension(148, 37));
        playersRoomGrid.add(player7);

        player8.setBackground(new java.awt.Color(255, 255, 255));
        player8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        player8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        player8.setMinimumSize(new java.awt.Dimension(148, 37));
        player8.setOpaque(true);
        player8.setPreferredSize(new java.awt.Dimension(148, 37));
        playersRoomGrid.add(player8);

        player1Status1.setBackground(new java.awt.Color(255, 255, 255));
        player1Status1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        player1Status1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        player1Status1.setMinimumSize(new java.awt.Dimension(148, 37));
        player1Status1.setOpaque(true);
        player1Status1.setPreferredSize(new java.awt.Dimension(148, 37));
        playersRoomGrid.add(player1Status1);

        player2Status1.setBackground(new java.awt.Color(255, 255, 255));
        player2Status1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        player2Status1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        player2Status1.setMinimumSize(new java.awt.Dimension(148, 37));
        player2Status1.setOpaque(true);
        player2Status1.setPreferredSize(new java.awt.Dimension(148, 37));
        playersRoomGrid.add(player2Status1);

        player3Status1.setBackground(new java.awt.Color(255, 255, 255));
        player3Status1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        player3Status1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        player3Status1.setMinimumSize(new java.awt.Dimension(148, 37));
        player3Status1.setOpaque(true);
        player3Status1.setPreferredSize(new java.awt.Dimension(148, 37));
        playersRoomGrid.add(player3Status1);

        player4Status1.setBackground(new java.awt.Color(255, 255, 255));
        player4Status1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        player4Status1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        player4Status1.setMinimumSize(new java.awt.Dimension(148, 37));
        player4Status1.setOpaque(true);
        player4Status1.setPreferredSize(new java.awt.Dimension(148, 37));
        playersRoomGrid.add(player4Status1);

        roomPage.add(playersRoomGrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pageBackground.png"))); // NOI18N
        jLabel9.setMaximumSize(new java.awt.Dimension(500, 550));
        jLabel9.setMinimumSize(new java.awt.Dimension(500, 550));
        jLabel9.setPreferredSize(new java.awt.Dimension(500, 550));
        roomPage.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        basePanel.add(roomPage, "roomP");

        mainFramePanel.add(basePanel, java.awt.BorderLayout.WEST);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mainFramePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mainFramePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoBActionPerformed
        quitConfirm.dispose();
    }//GEN-LAST:event_NoBActionPerformed

    private void yesBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesBActionPerformed
        quitConfirm.dispose();
        ClientService clientService = ClientService.getInstance();
        clientService.logoutRequest(username);
        this.dispose();
    }//GEN-LAST:event_yesBActionPerformed

    private void chatinputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_chatinputFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_chatinputFocusGained

    private void chatinputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_chatinputFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_chatinputFocusLost

    private void chatinputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatinputActionPerformed
        ClientService clientService = ClientService.getInstance();
        clientService.sendChat(username, chatinput.getText());
        chatinput.setText("");
    }//GEN-LAST:event_chatinputActionPerformed

    private void inviteB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inviteB2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inviteB2ActionPerformed

    private void sendmessageB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendmessageB2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sendmessageB2ActionPerformed

    private void playerList2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playerList2MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_playerList2MouseReleased

    private void homeB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeB1ActionPerformed
        selectPage("mainP");
    }//GEN-LAST:event_homeB1ActionPerformed

    private void rankingB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rankingB1ActionPerformed

    }//GEN-LAST:event_rankingB1ActionPerformed

    private void settingsB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsB1ActionPerformed
        selectPage("settingP");
    }//GEN-LAST:event_settingsB1ActionPerformed

    private void logoutB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutB1ActionPerformed
        quitConfirm.setVisible(true);
    }//GEN-LAST:event_logoutB1ActionPerformed

    private void joinBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinBActionPerformed
        int row = roomTable.getSelectedRow();
        room = roomTable.getModel().getValueAt(row, 0).toString();
        System.out.println("JoinRoom: "+ room);
        ClientService clientService = ClientService.getInstance();
        clientService.joinRoom(room);
    }//GEN-LAST:event_joinBActionPerformed

    private void createBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBActionPerformed
        selectPage("newRoomP");
    }//GEN-LAST:event_createBActionPerformed

    private void newEmailInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newEmailInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newEmailInputActionPerformed

    private void confirmPassInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPassInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmPassInputActionPerformed

    private void PlayersNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayersNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlayersNumberActionPerformed

    private void roomNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomNameInputActionPerformed

    private void privateGameCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_privateGameCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_privateGameCheckBoxActionPerformed

    private void backBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBActionPerformed
        selectPage("mainP");
    }//GEN-LAST:event_backBActionPerformed

    private void createRoomBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createRoomBActionPerformed
        ClientService clientService = ClientService.getInstance();
        int nPlayers = 2;
        //System.out.println(PlayersNumber.getSelectedItem());
        switch(PlayersNumber.getSelectedItem().toString()){
            case "2 Players":
                nPlayers = 2;
                break;
            case "3 Players":
                nPlayers = 3;
                break;
            case "4 Players":
                nPlayers = 4;
                break;     
        }
        clientService.createRoom(nPlayers, username);
        selectPage("roomOwnerP");
    }//GEN-LAST:event_createRoomBActionPerformed

    private void startBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startBActionPerformed

    private void quitBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitBActionPerformed
        ClientService clientService = ClientService.getInstance();
        clientService.quitRoom(username, room);
        selectPage("homeP");
    }//GEN-LAST:event_quitBActionPerformed

    private void quitRoomBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitRoomBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quitRoomBActionPerformed

    private void readyBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readyBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_readyBActionPerformed

        /**
     * Changes homegui front Page (selects card to show from CardLayout)
     * 
     * @param page The page you want to show. Choose between one of these strings: "homeP", "signupP", "loginP", helpP".
     */
    public void selectPage(String page){
        CardLayout card = (CardLayout) basePanel.getLayout();
        card.show(basePanel, page);   
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ChatP;
    private javax.swing.JButton NoB;
    private javax.swing.JComboBox<String> PlayersNumber;
    private javax.swing.JTabbedPane TabsTableRank;
    private javax.swing.JButton backB;
    private javax.swing.JPanel basePanel;
    public javax.swing.JPanel chatPanel;
    public javax.swing.JTextArea chatarea;
    private javax.swing.JTextField chatinput;
    private javax.swing.JPasswordField confirmPassInput;
    private javax.swing.JLabel confirmPassL;
    private javax.swing.JButton createB;
    private javax.swing.JButton createRoomB;
    private javax.swing.JPasswordField currentPassInput;
    private javax.swing.JLabel currentPassL;
    private javax.swing.JButton helpB1;
    private javax.swing.JButton homeB1;
    private javax.swing.JButton inviteB2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JButton joinB;
    private javax.swing.JButton logoutB1;
    private javax.swing.JPanel mainFramePanel;
    private javax.swing.JPanel mainPage;
    private javax.swing.JPanel menuBarSettings;
    private javax.swing.JTextField newEmailInput;
    private javax.swing.JLabel newEmailL;
    private javax.swing.JPasswordField newPassInput;
    private javax.swing.JLabel newPassL;
    private javax.swing.JPanel newRoomPage;
    private javax.swing.JLabel player1;
    private javax.swing.JLabel player1Status;
    private javax.swing.JLabel player1Status1;
    private javax.swing.JLabel player2;
    private javax.swing.JLabel player2Status;
    private javax.swing.JLabel player2Status1;
    private javax.swing.JLabel player3;
    private javax.swing.JLabel player3Status;
    private javax.swing.JLabel player3Status1;
    private javax.swing.JLabel player4;
    private javax.swing.JLabel player4Status;
    private javax.swing.JLabel player4Status1;
    private javax.swing.JLabel player5;
    private javax.swing.JLabel player6;
    private javax.swing.JLabel player7;
    private javax.swing.JLabel player8;
    public javax.swing.JTable playerList2;
    private javax.swing.JPanel playersGrid;
    private javax.swing.JPanel playersPanel;
    private javax.swing.JPanel playersRoomGrid;
    private javax.swing.JCheckBox privateGameCheckBox;
    private javax.swing.JPanel profsOptPanel2;
    private javax.swing.JButton quitB;
    private javax.swing.JDialog quitConfirm;
    private javax.swing.JButton quitRoomB;
    private javax.swing.JButton rankingB1;
    private javax.swing.JPanel rankingP;
    private javax.swing.JButton readyB;
    private javax.swing.JTextField roomNameInput;
    private javax.swing.JLabel roomNameLabel;
    private javax.swing.JPanel roomOwnerPage;
    private javax.swing.JPanel roomPage;
    private javax.swing.JScrollPane roomScrollPane;
    public javax.swing.JTable roomTable;
    private javax.swing.JButton sendmessageB2;
    private javax.swing.JButton settingsB1;
    private javax.swing.JPanel settingsPage;
    private javax.swing.JButton startB;
    private javax.swing.JLabel usernameL;
    private javax.swing.JLabel volumeL;
    private javax.swing.JSlider volumeSlider;
    private javax.swing.JLabel welcome;
    private javax.swing.JButton yesB;
    // End of variables declaration//GEN-END:variables
}
